{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-diversity
  version: {{ version }}

source:
  path: ../..

build:
  script: python setup.py install

requirements:
  build:
    - python 3.5*
    - setuptools

  run:
    - python 3.5*
    - setuptools
    - numpy
    - scipy
    - pandas
    - statsmodels
    - seaborn
    # `ipywidgets` included to avoid ShimWarning from
    # `seaborn` imports:
    #  https://github.com/mwaskom/seaborn/issues/874
    - ipywidgets
    - scikit-bio
    - biom-format >=2.1.5,<2.2.0
    - qiime2 {{ release }}.*
    - q2templates {{ release }}.*
    - q2-types {{ release }}.*
    - q2-feature-table {{ release }}.*

test:
  imports:
    - q2_diversity
    - qiime2.plugins.diversity

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
