{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-diversity
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  build:
    - python 3.5*
    - setuptools
    - nodejs

  run:
    - python 3.5*
    - setuptools
    - numpy
    - scipy
    - pandas
    - statsmodels
    - seaborn
    # `ipywidgets` included to avoid ShimWarning from
    # `seaborn` imports:
    #  https://github.com/mwaskom/seaborn/issues/874
    - ipywidgets
    - scikit-bio
    - scikit-learn
    - psutil
    - natsort
    - biom-format >=2.1.5,<2.2.0
    - unifrac >=0.9.2,<0.10.0
    - qiime2 {{ release }}.*
    - q2templates {{ release }}.*
    - q2-types {{ release }}.*
    - q2-feature-table {{ release }}.*
    # TODO: `emperor` is also a dependency, but q2-emperor should be in charge
    # of the version pin. Eventually there will not be a direct dependency on
    # `emperor` and this comment can be removed.
    - q2-emperor {{ release }}.*

test:
  imports:
    - q2_diversity
    - qiime2.plugins.diversity

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
